### PR TITLE
Fix minor exercise issue

### PR DESCRIPTION
**Pull request by parker-codes**
Turns out 2 of the things I noticed were already fixed. 🙂

Screenshot 2023-02-10 at 2 26 52 PM

### CODE REVIEW

**Comment by parker-codes** [comment]
Also, thanks for creating such a good resource on one of the hardest things to learn in Rust! ❤️

**Comment by tfpk** [comment]
I'm sorry to say that I *think* (and I might be going crazy here) the issue in this PR has also been fixed. I got a wave of PRs from @ctm which I've only just accepted, which is probably where the fix came from.

I really appreciate your finding all those issues, thank you very much for caring about the project enough to go to the effort! If there's anything else I've missed please please do fill out a PR and I'd be very grateful.

**Comment by tfpk** [comment]
> Also, thanks for creating such a good resource on one of the hardest things to learn in Rust! heart

And thank you very much! Glad you enjoyed it :)

**Comment by tfpk** [comment]
Ah, I just saw the space-under-import thing: I'll grab that now.

**Pull request merged**
