### PR TITLE
(review needed!) Correct sentence in Ch6

### PR DESCRIPTION
**Pull request by skaunov**
I'm not a native speaker, but to me this second "of" looks like a typo.

(sorry for exclamation --- I worry to break the meaning with some small innocent looking edit)

### CODE REVIEW

**Comment by tfpk** [comment]
Definitely a typo, but I think it's meant to be saying "the lifetime of the borrow of self". I'll read over this again tonight to double check (am on mobile now), but thanks for pointing it out!

**Comment by skaunov** [comment]
Maybe it's a sign that this part deserves a bit deeper copyediting. :idk:On May 29, 2023 1:12 AM, Tom Kunc ***@***.***> wrote:
Definitely a typo, but I think it's meant to be saying "the lifetime of the borrow of self". I'll read over this again tonight to double check (am on mobile now), but thanks for pointing it out!

**Comment by tfpk** [comment]
I can't edit your branch for some reason. Would you be able to edit it to something like:

> the lifetime of the borrow of `self` is assigned to all elided output lifetimes.

I'd be more than happy to do more copy-editing, though reading over it all makes sense to me. Alas, it's hard to edit something when you're the one who wrote it.

If you have any suggestions for other places that need rewording, they'd be much appreciated.

**Comment by skaunov** [comment]
Yeah, it do behave strangely. "Allow edits by maintainers" is enabled though.
> I can't edit your branch for some reason. Would you be able to edit it to something like:
> 
> > the lifetime of the borrow of `self` is assigned to all elided output lifetimes.
> 

I have this problem too usually. =( Will give it a try! Though I'm not a good editor, at least in English. X)
> ... it's hard to edit something when you're the one who wrote it.
> 
> If you have any suggestions for other places that need rewording, they'd be much appreciated.

**Comment by tfpk** [comment]
Thanks for the change! Please feel free to PR any other improvements you find :)

**Pull request merged**
